server:
  port: 8081

spring:
  application:
    name: spring-dubbo

dubbo:
  scan:
    base-packages: com.leone.boot.dubbo.provider.service.impl
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A
  application:
    name: dubbo-provider
