spring:
  datasource:
    url: jdbc:mysql://ip:3306/boot?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: cloud
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template-location: false


mybatis:
  type-aliases-package: com.leone.shiro.entity
  mapper-locations: classpath:mybatis/mappers/*.xml

app:
  shiro:
    cacheTime: 4320
    redisPrefix: shiro:${server.port}
    tokenPrefix: auth.token.
    anonUrls:
      - /login
      - /image
      - /api/shiro/user/account
    authUrls: /**


