server:
  port: 8081

customer:
  msg: jack
  property:
  - first-name: zhang
    last-name: san
  - first-name: liu
    last-name: sheng

module:
  shiro:
    cacheTime: 1080
    tokenSecret: J(#_=*!A
    tokenPrefix: "shiro:token:${server.port}:"
    anonUrls:
      - /api/login
      - /api/logout
    authUrls: /**


