server:
  port: 8081

customer:
  msg: jack
  property:
  - first-name: wang
    last-name: lao
  - first-name: li
    last-name: sheng

module:
  shiro:
    cacheTime: 7
    tokenSecret: J(#_=*!A
    redisPrefix: shiro.auth.token:${server.port}
    anonUrls: /test
    authUrls: /**
