customer:
  msg: jack
  property:
  - first-name: wang
    last-name: lao
  - first-name: li
    last-name: sheng
module:
  shiro:
    cacheDays: 7
    redisPrefix: ${server.port}
    anonUrls: /**
    coreUrls:
    - /api/user/property
    - /api/user/login
    authUrls: /hello
    tokenPrefix: ${server.port}
    tokenName: auth.token
